- name : configure catalogue server
  hosts: catalogue
  become : yes
  tasks:
  - name: disable default nodejs
    ansible.builtin,command: dnf module disable nodejs -y
  
  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create a roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin # No login shell
      system: true  # System user
      home: /app   # Home directory

  - name: create app directory
    ansible.builtin.file:
     name: /app
     state: directory

  - name: Download the catalogue code
    ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
    dest: /tmp/catalogue.zip

# this module thinks file exist on ansible control server, needs to extract on to remote machine
# remote_src: yes means files already exist in catalogue server

  - name: unzip the catalogue code
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip #
      dest: /app
      remote_src: yes # Extract on remote machine

  - name: Install dependencies
    community.general.npm:
    name: npm install
    path: /app

  - name: copy catalogue service file
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: systemctl deamon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Start and enable catalogue service
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes

  - name: copy mongodb service file
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present

  - name: check products loaded or not
    ansible.builtin.command: mongosh --host mongodb.akashabalaji.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    result: catalogue_output

  - name: print the catalogue output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: load products
    ansible.builtin.shell: mongosh --host mongodb.daws84s.site < /app/db/master-data.js
    when: catalogue_output.stdout | int < 0