# Preflight: wait for MySQL to be reachable (from shipping host)
- name: Wait for MySQL to be up
  ansible.builtin.wait_for:
    host: mysql.akashabalaji.site
    port: 3306
    timeout: 60

# Try to clear any prior host blocks (uses the new admin user)
- name: Flush MySQL blocked hosts
  community.mysql.mysql_query:
    login_host: mysql.akashabalaji.site
    login_user: dbadmin
    login_password: "StrongPass!ChangeMe"
    query: "FLUSH HOSTS;"
  register: flush_hosts_result
  failed_when: false   # don't fail if it wasn't needed
  run_once: true

# Import the SQL files with the admin user (NOT root)
- name: Import data
  tags:
    - import
  community.mysql.mysql_db:
    name: all
    state: import
    login_host: mysql.akashabalaji.site
    login_user: dbadmin
    login_password: "StrongPass!ChangeMe"
    target: "{{ item }}"
    connect_timeout: 30
  loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql
    - /app/db/master-data.sql
  retries: 3
  delay: 5
  register: import_result
  until: import_result is succeeded

# Restart shipping only if import changed something
- name: restart shipping
  tags:
    - import
  ansible.builtin.service:
    name: shipping
    state: restarted
  when: import_result.changed
